# Generated by Django 5.0.4 on 2024-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='partner',
            field=models.ForeignKey(default=1000, on_delete=models.SET(1000), related_name='records', to='records.partner'),
        ),
    ]
